title: GitHub Badges
description: Complete list of all GitHub Profile badges and Achievements
theme: just-the-docs

url: https://github-profile-achievements.github.io/english/

aux_links:
    Template Repository: https://github.com/github-profile-achievements/english

# Set a path/url to a logo that will be displayed instead of the title
# TODO logo: "/assets/images/just-the-docs.png"

# Set a path/url to a favicon that will be displayed by the browser
# TODO favicon_ico: "/assets/images/favicon.ico"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
    "Badges & achievements on GitHub":
        - "https://github.com/github-profile-achievements/english"

# Makes Aux links open in a new tab.
aux_links_new_tab: true
